# Создание массивов из списков(Py_WP, стр. 64)

In [1]:
import numpy as np

In [2]:
np.array([1, 4, 2, 5]) # Numpy массив содержит элементы одного типа

array([1, 4, 2, 5])

In [3]:
np.array([3.14, 4, 2, 3])  # Если типы элементов не сопадают, Numpy попытается выполнить повышающее приведение типов

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')  # Можно задать тип вручную

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])  # Вложенные списки преобразуются в многомерный массив

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Создание массивов с нуля(Py_WP, стр.65)

In [6]:
# Создание массивов с нуля
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((4, 6), dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
np.full((5, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [9]:
np.arange(0, 18, 3)  # Аналогично встроенной функции range()

array([ 0,  3,  6,  9, 12, 15])

In [10]:
np.linspace(0, 3, 10)   # Создаем массв из десяти значений равномерно распологающихся между 0 и 3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [11]:
np.random.random((3, 4)) # Создаем массив разиером 3х4 нормально распределенных случайных значений от 0 до 1

array([[0.89047424, 0.80559927, 0.77101034, 0.34693763],
       [0.29341748, 0.67200802, 0.44784151, 0.01351367],
       [0.73502934, 0.22335497, 0.0373645 , 0.9872326 ]])

In [12]:
# Создаем массив размером 3х5 нормально распределенных 
# случайных значений c медианой 0 и стандартным отклонением 1
np.random.normal(0, 1, (3, 5)) 

array([[ 1.32188276, -0.59979872,  0.83712766,  0.10813835,  0.5568877 ],
       [ 1.36592734,  0.6126832 ,  0.25583353,  0.8788819 ,  0.71114536],
       [ 0.07752013, -0.45325692, -0.30113628,  0.49350428, -0.54439235]])

In [13]:
# создание массива случайных целых чисел в промежутке [0, 20]
np.random.randint(0, 20, (10, 10))

array([[ 6,  6,  1,  1, 11, 16, 18,  5,  7, 14],
       [15, 16,  6, 14, 17, 14, 11,  0,  9, 11],
       [12, 13,  2, 11, 19,  7,  0,  7,  8, 11],
       [ 3, 12,  8, 14, 17,  8, 16, 10, 17,  9],
       [10, 14, 11,  6, 10,  5, 12, 12,  3, 14],
       [12,  5,  9,  8,  7,  9,  3,  4, 15,  1],
       [ 1, 16,  0, 12,  7,  5, 16,  8,  0, 12],
       [13, 10,  6, 18,  2, 12,  3, 10, 19, 13],
       [11,  6, 10,  5,  8,  2, 15,  1, 10,  5],
       [ 2, 17, 15, 15,  7,  3,  8,  1,  3, 16]])

In [14]:
# Создание единичной матрицы
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Создание неинициализированного массива с произвольными значениями
np.empty(5)

array([9.45934269e-312, 5.31495570e+228, 1.24282155e+214, 1.57630801e-052,
       6.76999384e+170])

###### Стандартные типы данных Numpy(Py_WP, стр.66)

# Атрибуты массивов библиотеки Numpy(Py_WP, стр. 68)

In [16]:
np.random.seed(0)   # Изначальное значение для целей воспроизводимости

x1 = np.random.randint(5, size=4) # Одномерный массив
x2 = np.random.randint(5, size=(3, 4))  # Двумерный массив
x3 = np.random.randint(5, size=(2, 3, 4))  # Трехмерный массив
print('x1', x1, 'x2', x2, 'x3', x3, sep='\n')

x1
[4 0 3 3]
x2
[[3 1 3 2]
 [4 0 0 4]
 [2 1 0 1]]
x3
[[[1 0 1 4]
  [3 0 3 0]
  [2 3 0 1]]

 [[3 3 3 0]
  [1 1 1 0]
  [2 4 3 3]]]


In [17]:
print('x3 ndim:', x3.ndim, sep='  ')
print('x3 shape:', x3.shape)
print('x3 size:', x3.size, sep='  ')
print('x3 dtype:', x3.dtype)

x3 ndim:  3
x3 shape: (2, 3, 4)
x3 size:  24
x3 dtype: int32


In [18]:
print('itemsize', x3.itemsize, 'bytes')   # Размер элемента в байтах
print('nbytes', x3.nbytes, 'bytes')  # Полный размер массива в байтах

itemsize 4 bytes
nbytes 96 bytes


In [19]:
x1

array([4, 0, 3, 3])

In [20]:
x1[2]

3

In [21]:
x1[-3]

0

In [22]:
x1[0] = 3.14  # Это значение будет усечено 
x1

array([3, 0, 3, 3])

In [23]:
x2

array([[3, 1, 3, 2],
       [4, 0, 0, 4],
       [2, 1, 0, 1]])

In [24]:
x2[1, 0]

4

In [25]:
 x2[2, -1]

1

In [26]:
x2[0, 1] = 11
x2

array([[ 3, 11,  3,  2],
       [ 4,  0,  0,  4],
       [ 2,  1,  0,  1]])

## Срезы(Py_WP, p.70)

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[4:7]

array([4, 5, 6])

In [30]:
x[1::2]

array([1, 3, 5, 7, 9])

In [31]:
x[7:2:-2]

array([7, 5, 3])

### Многомерные подмассивы(Py_WP, p.71)

In [32]:
x2

array([[ 3, 11,  3,  2],
       [ 4,  0,  0,  4],
       [ 2,  1,  0,  1]])

In [33]:
x2[:2, :3]  # Две строки, три столбца

array([[ 3, 11,  3],
       [ 4,  0,  0]])

In [34]:
x2[1:, 1:]

array([[0, 0, 4],
       [1, 0, 1]])

In [35]:
x2[:,::2]  #  Все строки, столбцы через один

array([[3, 3],
       [4, 0],
       [2, 0]])

In [36]:
x2[::-1, ::-1]   # Переворот массива

array([[ 1,  0,  1,  2],
       [ 4,  0,  0,  4],
       [ 2,  3, 11,  3]])

In [37]:
x2[:, ::-2]

array([[ 2, 11],
       [ 4,  0],
       [ 1,  1]])

In [38]:
x2[:, ::-2][:, ::-1] # Двойная индексация

array([[11,  2],
       [ 0,  4],
       [ 1,  1]])

## Доступ к строкам и столбцам(Py_WP, p.72)

In [39]:
x2

array([[ 3, 11,  3,  2],
       [ 4,  0,  0,  4],
       [ 2,  1,  0,  1]])

In [40]:
print(x2[:, 0])    # Первый столбец 

[3 4 2]


In [41]:
print(x2[0, :])    # Первая строка
print(x2[0])       # Аналогично

[ 3 11  3  2]
[ 3 11  3  2]


## Подмассив - представление(Py_WP, p.72)

In [42]:
x2_v = x2[:2, :2]   # Работают как представления(view)
print('изначальный массив', x2, 'двумерный подмассив', x2_v, sep='\n')
print('Меняем первый элемент подмассива на 100')
x2_v[0, 0] = 100
print('изначальный массив', x2, 'двумерный подмассив', x2_v, 'меняется также и изначальный массив', sep='\n') 

изначальный массив
[[ 3 11  3  2]
 [ 4  0  0  4]
 [ 2  1  0  1]]
двумерный подмассив
[[ 3 11]
 [ 4  0]]
Меняем первый элемент подмассива на 100
изначальный массив
[[100  11   3   2]
 [  4   0   0   4]
 [  2   1   0   1]]
двумерный подмассив
[[100  11]
 [  4   0]]
меняется также и изначальный массив


In [43]:
x2_sub_copy = x2[:2, :2].copy()   # Создается копия
print('изначальный массив', x2, 'копия двумерного подмассива', x2_sub_copy, sep='\n')
print('Меняем первый элемент подмассива на 44')
x2_sub_copy[0, 0] = 44
print('изначальный массив', x2, 'копия', x2_sub_copy, 'изначальный массив остается без изменений', sep='\n') 

изначальный массив
[[100  11   3   2]
 [  4   0   0   4]
 [  2   1   0   1]]
копия двумерного подмассива
[[100  11]
 [  4   0]]
Меняем первый элемент подмассива на 44
изначальный массив
[[100  11   3   2]
 [  4   0   0   4]
 [  2   1   0   1]]
копия
[[44 11]
 [ 4  0]]
изначальный массив остается без изменений


## Изменение формы массивов(Py_WP, p.74)

In [44]:
grid = np.arange(1, 17).reshape((4, 4))
print(grid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [45]:
x1 = np.arange(1, 4)
x1

array([1, 2, 3])

In [46]:
x1.reshape(1, 3)  # Преобразование в вектор-строку с помощью reshape

array([[1, 2, 3]])

In [47]:
x1[np.newaxis, :]  # Преобразование в вектор-строку с помощью newaxis

array([[1, 2, 3]])

In [48]:
x1.reshape(3, 1)  # Преобразование в вектор-столбец с помощью reshape

array([[1],
       [2],
       [3]])

In [49]:
x1[:, np.newaxis]  # Преобразование в вектор-столбец с помощью newaxis

array([[1],
       [2],
       [3]])

## Слияние массивов (Py_WP, p.75)

In [50]:
x1 = np.array([1, 2, 3])
y1 = np.arange(3, 0, -1)
z1 = np.array([99, 100, 101])
print(x1, y1, z1)

[1 2 3] [3 2 1] [ 99 100 101]


In [51]:
print(np.concatenate([x1, y1, z1]))

[  1   2   3   3   2   1  99 100 101]


In [52]:
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
np.concatenate([grid, grid]) # Объединение двумерных массивов

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [54]:
np.concatenate([grid, grid], axis=1)  # Объединение по второй оси координат

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

In [55]:
# Для объединения массивов у которых различаются измерения используют np.vstack и np.hstack
x1 = np.arange(1, 5)    # Одномерный массив
np.vstack([x1, grid])

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
x1 = x1[:, np.newaxis]
x1

array([[1],
       [2],
       [3],
       [4]])

In [57]:
np.hstack([grid, x1])

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  2],
       [ 9, 10, 11, 12,  3],
       [13, 14, 15, 16,  4]])

## Разбиение массивов(Py_WP, p.76)

In [58]:
x = np.array([1, 2, 3, 99, 100, 101, 5, 6, 7])
x

array([  1,   2,   3,  99, 100, 101,   5,   6,   7])

In [59]:
np.split(x, 3) # Разбиение на одинаковые по размеру массивы

[array([1, 2, 3]), array([ 99, 100, 101]), array([5, 6, 7])]

In [60]:
x1, x2, x3 = np.split(x, [2, 5])  # Разбиение по индексам
print(x1, x2, x3)

[1 2] [  3  99 100] [101   5   6   7]


In [61]:
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
np.vsplit(grid, 2)


[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [63]:
np.vsplit(grid, 4)


[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [64]:
np.vsplit(grid, [3])


[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), array([[13, 14, 15, 16]])]

In [65]:
left, right = np.hsplit(grid, 2)
print(left)
print(right)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [66]:
np.hsplit(grid, 4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]), array([[ 2],
        [ 6],
        [10],
        [14]]), array([[ 3],
        [ 7],
        [11],
        [15]]), array([[ 4],
        [ 8],
        [12],
        [16]])]

In [67]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 4]
 [ 8]
 [12]
 [16]]


In [68]:
x3 = np.random.randint(5, size=(2, 3, 4))  # Трехмерный массив

x3

array([[[2, 4, 2, 0],
        [0, 4, 0, 4],
        [1, 4, 1, 2]],

       [[2, 0, 1, 1],
        [1, 1, 3, 3],
        [2, 3, 0, 3]]])

In [69]:
np.dsplit(x3, 4) # Функция np.dsplit для третье оси

[array([[[2],
         [0],
         [1]],
 
        [[2],
         [1],
         [2]]]), array([[[4],
         [4],
         [4]],
 
        [[0],
         [1],
         [3]]]), array([[[2],
         [0],
         [1]],
 
        [[1],
         [3],
         [0]]]), array([[[0],
         [4],
         [2]],
 
        [[1],
         [3],
         [3]]])]